-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(sheets_record_lex).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/sheets_record_lex.xrl", 69).

parse_sheet(TokenChars) ->
    {match, [Name]} = re:run(get_uf8_binary(TokenChars), "\\(\\s*([a-z][0-9a-zA-Z_]*)\\s*,", [{capture,[1],list}]),
    list_to_atom(Name).

parse_field(TokenChars) ->
    TokenChars2 = trim(TokenChars, trailing, ","),
    [Name0|Rest] = string:tokens(TokenChars2, "="),
    Name = trim(Name0),
    Default = case trim(Rest) of
        [] -> undefined;
        Val -> eval(Val ++ ".")
    end,
    {list_to_atom(Name), Default}.

parse_comment(TokenChars) ->
    TokenChars2 = trim(TokenChars),
    TokenChars3 = trim(TokenChars2, leading, "%"),
    trim(TokenChars3, leading).

parse_method(TokenChars) ->
    [$@|TokenChars2] = trim(TokenChars),
    list_to_atom(TokenChars2).

parse_param_from_str(TokenChars) ->
    S = fetch_param_string(TokenChars),
    %io:format("parse_param_from_str ~p, ~p~n", [S, TokenChars]),
    S.

push_back_param_str(TokenChars) ->
    S = fetch_param_string(TokenChars),
    TokenChars2 = trim(TokenChars, leading, S),
    %io:format("push_back_param_str ~p, ~p~n", [S, TokenChars2]),
    TokenChars2.

fetch_param_string(TokenChars) ->
    {match, [SubStr]} = re:run(TokenChars, "(\"((\\\")|.)+\")", [{capture, first, list}, ungreedy]),
    SubStr.

parse_param(TokenChars) ->
    trim(TokenChars).

parse_modifier(TokenChars) ->
    TokenChars2 = trim(TokenChars),
    [$||TokenChars3] = trim(TokenChars2),
    list_to_atom(trim(TokenChars3)).

parse_logic(TokenChars) ->
    TokenChars2 = trim(TokenChars),
    TokenChars3 = trim(TokenChars2, leading, "->"),
    TokenChars4 = trim(TokenChars3, trailing, "|"),
    trim(TokenChars4).

push_back_method(TokenChars) ->
    {match, [Binary]} = re:run(get_uf8_binary(TokenChars), "(@[a-z][0-9a-zA-Z_]*.*)", [{capture,[1],binary}]),
    get_unicode(Binary).

get_uf8_binary(String) ->
    unicode:characters_to_binary(String).

get_unicode(Binary) when is_binary(Binary) ->
    unicode:characters_to_list(Binary);

get_unicode(Binary) -> get_unicode(iolist_to_binary(Binary)).

eval(S) ->
  {ok, Scanned, _} = erl_scan:string(S),
  {ok, Parsed} = erl_parse:parse_exprs(Scanned),
  {value, Value, _} = erl_eval:exprs(Parsed,[]),
  Value.
  

otp_ver() ->
    {match, [VerStr]} = re:run(erlang:system_info(otp_release), "^R?([0-9]+)", [{capture,[1],list}]),
    list_to_integer(VerStr).

has_string_trim() ->
    otp_ver() >= 20.

trim(S) -> trim(S, both).
trim(S, D) ->
    case has_string_trim() of
        true -> string:trim(S, D);
        false -> my_trim(S, D, " ")
    end.

trim(S, D, Chars) ->
    case has_string_trim() of
        true -> string:trim(S, D, Chars);
        false -> my_trim(S, D, Chars)
    end.

my_trim([S], D, List) when is_list(S) ->
    my_trim(S, D, List);

my_trim(S, D, [Sep]) ->
    D2 = case D of
        leading -> left;
        trailing -> right;
        both -> both
    end,
    string:strip(S, D2, Sep);
my_trim(S, leading, List) ->
    L = length(List),
    case string:substr(S, 1, L) of
        List -> string:substr(S, L + 1);
        _ -> S
    end.

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/sheets_record_lex.erl", 384).
yystate() -> 100.

yystate(107, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(107, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,107};
yystate(106, [101|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 10, Tlen);
yystate(106, [69|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 10, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(106, Ics, Line, Tlen+1, 10, Tlen);
yystate(106, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,106};
yystate(105, [101|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 6, Tlen);
yystate(105, [69|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 6, Tlen);
yystate(105, [44|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 6, Tlen);
yystate(105, [32|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(105, [9|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(105, Ics, Line, Tlen+1, 6, Tlen);
yystate(105, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,105};
yystate(104, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(104, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(104, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(104, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,104};
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(105, Ics, Line, Tlen+1, Action, Alen);
yystate(103, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,103};
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(102, Ics, Line, Tlen+1, 10, Tlen);
yystate(102, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,102};
yystate(101, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(100, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(96, Ics, Line+1, Tlen+1, Action, Alen);
yystate(100, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 101 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(100, [C|Ics], Line, Tlen, Action, Alen) when C >= 19968, C =< 40869 ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(100, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,100};
yystate(99, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(98, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(98, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,98};
yystate(97, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(97, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(97, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(97, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,97};
yystate(96, [13|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 17, Tlen);
yystate(96, [10|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line+1, Tlen+1, 17, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,96};
yystate(95, [46|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 6, Tlen);
yystate(95, [44|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 6, Tlen);
yystate(95, [32|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(95, [9|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(95, Ics, Line, Tlen+1, 6, Tlen);
yystate(95, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,95};
yystate(94, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(94, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,94};
yystate(93, [101|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 10, Tlen);
yystate(93, [69|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 10, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,93};
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 19968, C =< 40869 ->
    yystate(92, Ics, Line, Tlen+1, 10, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,92};
yystate(91, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(90, [46|Ics], Line, Tlen, _, _) ->
    yystate(98, Ics, Line, Tlen+1, 10, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(90, Ics, Line, Tlen+1, 10, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,90};
yystate(89, [44|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 6, Tlen);
yystate(89, [32|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(89, [9|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(89, Ics, Line, Tlen+1, 6, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,89};
yystate(88, [95|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [32|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,88};
yystate(87, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 90 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Tlen, Action, Alen) when C >= 94 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(86, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,86};
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(84, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,84};
yystate(83, [64|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [37|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [32|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [9|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 63 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,83};
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 10, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(82, Ics, Line, Tlen+1, 10, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(82, Ics, Line, Tlen+1, 10, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(82, Ics, Line, Tlen+1, 10, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,82};
yystate(81, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(81, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,81};
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [40|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [32|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,80};
yystate(79, [95|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [44|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [32|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [9|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,79};
yystate(78, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 113 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [C|Ics], Line, Tlen, Action, Alen) when C >= 115, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,78};
yystate(77, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [64|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 96 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(59, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,75};
yystate(74, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(74, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [110|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [32|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,72};
yystate(71, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 100 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [124|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, [11|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, [12|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 123 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 125 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,69};
yystate(68, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(67, [64|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 96 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(59, Ics, Line, Tlen+1, 1, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,67};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 7, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(66, Ics, Line, Tlen+1, 7, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(66, Ics, Line, Tlen+1, 7, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(66, Ics, Line, Tlen+1, 7, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,66};
yystate(65, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [117|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [32|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(88, Ics, Line, Tlen+1, 5, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(62, [99|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [97|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [98|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [96|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,62};
yystate(61, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(60, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [96|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [64|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(59, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 63 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(59, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(59, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,59};
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [102|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 18, Tlen);
yystate(56, [63|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 18, Tlen);
yystate(56, [32|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 18, Tlen);
yystate(56, [9|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 18, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(88, Ics, Line, Tlen+1, 18, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(88, Ics, Line, Tlen+1, 18, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,56};
yystate(55, [44|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [32|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, [9|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 6, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,55};
yystate(54, [111|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [96|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,54};
yystate(53, [124|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [32|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [11|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [12|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [9|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 123 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 125 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,53};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 15, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,52};
yystate(51, [64|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,51};
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 10, Tlen);
yystate(50, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 10, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 10, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(50, Ics, Line, Tlen+1, 10, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(50, Ics, Line, Tlen+1, 10, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,50};
yystate(49, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 33, C =< 123 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 125 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,49};
yystate(48, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 122 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 126 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [114|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [96|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,46};
yystate(45, [92|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [44|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [34|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [33|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [32|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [9|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 43 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 91 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,45};
yystate(44, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 122 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 126 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, [64|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [37|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [32|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [9|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 63 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,43};
yystate(42, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 94 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [92|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [34|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,40};
yystate(39, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [100|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [96|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,38};
yystate(37, [92|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(37, [34|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 6, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,37};
yystate(36, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(35, [64|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(4, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(4, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,35};
yystate(34, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,33};
yystate(32, [117|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [32|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,32};
yystate(31, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [96|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [40|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 39 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 41, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,30};
yystate(29, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 31 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 43 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 45, C =< 91 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, [64|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Tlen+1, 0, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(4, Ics, Line, Tlen+1, 0, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 96 ->
    yystate(4, Ics, Line, Tlen+1, 0, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(4, Ics, Line, Tlen+1, 0, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,27};
yystate(26, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(25, [96|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,25};
yystate(24, [110|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [32|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,24};
yystate(23, [101|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(0, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(0, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 102 ->
    yystate(0, Ics, Line, Tlen+1, 10, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,23};
yystate(22, [96|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [44|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 43 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 64 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(22, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(22, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,22};
yystate(21, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, [64|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 2, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,20};
yystate(19, [64|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 96 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,19};
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(18, Ics, Line, Tlen+1, 10, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,18};
yystate(17, [32|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [9|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 96 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(22, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,17};
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [40|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [32|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,16};
yystate(15, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 99 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 102 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [13|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 3, Tlen);
yystate(14, [11|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 3, Tlen);
yystate(14, [12|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 3, Tlen);
yystate(14, [10|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line+1, Tlen+1, 3, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 3, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 14 ->
    yystate(33, Ics, Line, Tlen+1, 3, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,14};
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [44|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [32|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [9|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, 5, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,13};
yystate(12, [64|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 2, Tlen);
yystate(12, [32|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(12, [9|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 2, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 63 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(20, Ics, Line, Tlen+1, 2, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,12};
yystate(11, [96|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [64|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 58, C =< 63 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 91, C =< 94 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 123 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,11};
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 10, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, 10, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Tlen+1, 10, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Tlen+1, 10, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,10};
yystate(9, [123|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [32|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [9|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 122 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 124 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,9};
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 11 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 100 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 109 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 111 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, [13|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 3, Tlen);
yystate(6, [10|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line+1, Tlen+1, 3, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,6};
yystate(5, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [64|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Tlen+1, 0, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(4, Ics, Line, Tlen+1, 0, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(4, Ics, Line, Tlen+1, 0, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,4};
yystate(3, [64|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 0, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 63 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65 ->
    yystate(3, Ics, Line, Tlen+1, 0, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,3};
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 10, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 10, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(2, Ics, Line, Tlen+1, 10, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(2, Ics, Line, Tlen+1, 10, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,2};
yystate(1, [32|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, [13|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, [11|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, [12|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, [10|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line+1, Tlen+1, 4, Tlen);
yystate(1, [9|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 33 ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,1};
yystate(0, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 100 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 102 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    yyaction_0();
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, _, _, _) ->
    yyaction_4();
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, _) ->
    yyaction_17();
yyaction(18, _, _, _) ->
    yyaction_18();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("src/sheets_record_lex.xrl", 27).
yyaction_0() ->
     skip_token .

-compile({inline,yyaction_1/2}).
-file("src/sheets_record_lex.xrl", 29).
yyaction_1(TokenChars, TokenLine) ->
     { token, { sheet_def_comment, TokenLine, parse_comment (TokenChars) }, push_back_method (TokenChars) } .

-compile({inline,yyaction_2/2}).
-file("src/sheets_record_lex.xrl", 31).
yyaction_2(TokenChars, TokenLine) ->
     { token, { sheet_def_comment, TokenLine, parse_comment (TokenChars) } } .

-compile({inline,yyaction_3/2}).
-file("src/sheets_record_lex.xrl", 33).
yyaction_3(TokenChars, TokenLine) ->
     { token, { sheet_def_record, TokenLine, parse_sheet (TokenChars) } } .

-compile({inline,yyaction_4/0}).
-file("src/sheets_record_lex.xrl", 35).
yyaction_4() ->
     skip_token .

-compile({inline,yyaction_5/2}).
-file("src/sheets_record_lex.xrl", 37).
yyaction_5(TokenChars, TokenLine) ->
     { token, { sheet_def_field, TokenLine, parse_field (TokenChars) } } .

-compile({inline,yyaction_6/2}).
-file("src/sheets_record_lex.xrl", 39).
yyaction_6(TokenChars, TokenLine) ->
     { token, { sheet_def_field, TokenLine, parse_field (TokenChars) } } .

-compile({inline,yyaction_7/2}).
-file("src/sheets_record_lex.xrl", 41).
yyaction_7(TokenChars, TokenLine) ->
     { token, { sheet_def_method, TokenLine, parse_method (TokenChars) } } .

-compile({inline,yyaction_8/1}).
-file("src/sheets_record_lex.xrl", 43).
yyaction_8(TokenLine) ->
     { token, { sheet_def_param_start, TokenLine } } .

-compile({inline,yyaction_9/2}).
-file("src/sheets_record_lex.xrl", 45).
yyaction_9(TokenChars, TokenLine) ->
     { token, { sheet_def_param, TokenLine, parse_param_from_str (TokenChars) }, push_back_param_str (TokenChars) } .

-compile({inline,yyaction_10/2}).
-file("src/sheets_record_lex.xrl", 47).
yyaction_10(TokenChars, TokenLine) ->
     { token, { sheet_def_param, TokenLine, parse_param (TokenChars) } } .

-compile({inline,yyaction_11/1}).
-file("src/sheets_record_lex.xrl", 49).
yyaction_11(TokenLine) ->
     { token, { sheet_def_param_delimiter, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/sheets_record_lex.xrl", 51).
yyaction_12(TokenLine) ->
     { token, { sheet_def_param_end, TokenLine } } .

-compile({inline,yyaction_13/2}).
-file("src/sheets_record_lex.xrl", 53).
yyaction_13(TokenChars, TokenLine) ->
     { token, { sheet_def_logic, TokenLine, parse_logic (TokenChars) }, "|" } .

-compile({inline,yyaction_14/2}).
-file("src/sheets_record_lex.xrl", 55).
yyaction_14(TokenChars, TokenLine) ->
     { token, { sheet_def_logic, TokenLine, parse_logic (TokenChars) } } .

-compile({inline,yyaction_15/2}).
-file("src/sheets_record_lex.xrl", 57).
yyaction_15(TokenChars, TokenLine) ->
     { token, { sheet_def_modifier, TokenLine, parse_modifier (TokenChars) } } .

-compile({inline,yyaction_16/1}).
-file("src/sheets_record_lex.xrl", 59).
yyaction_16(TokenLine) ->
     { token, { sheet_def_end, TokenLine } } .

-compile({inline,yyaction_17/0}).
-file("src/sheets_record_lex.xrl", 61).
yyaction_17() ->
     skip_token .

-compile({inline,yyaction_18/0}).
-file("src/sheets_record_lex.xrl", 63).
yyaction_18() ->
     skip_token .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 282).
